In [1]:
import numpy as np

def prediction(X, theta):
    """다중 선형 회귀 가설 함수. 모든 데이터에 대한 예측 값을 numpy 배열로 리턴한다"""
    # 여기에 코드를 작성하세요
    return X @ theta

# 입력 변수
house_size = np.array([1.0, 1.5, 1.8, 5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 6.0, 7.0, 8.0, 8.5, 9.0, 10.0])  # 집 크기
distance_from_station = np.array([5, 4.6, 4.2, 3.9, 3.9, 3.6, 3.5, 3.4, 2.9, 2.8, 2.7, 2.3, 2.0, 1.8, 1.5, 1.0])  # 지하철역으로부터의 거리 (km)
number_of_rooms = np.array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])  # 방 수

# 설계 행렬 X 정의
X = np.array([
    np.ones(16),
    house_size,
    distance_from_station,
    number_of_rooms
]).T

# 파라미터 theta 값 정의
theta = np.array([1, 2, 3, 4])

prediction(X, theta)

array([22. , 21.8, 21.2, 26.7, 24.7, 24.8, 25.5, 26.2, 29.7, 31.4, 33.1,
       33.9, 39. , 39.4, 39.5, 40. ])

In [2]:
import numpy as np

def prediction(X, theta):
    """다중 선형 회귀 가정 함수. 모든 데이터에 대한 예측 값을 numpy 배열로 리턴한다"""
    # 지난 실습의 코드를 여기에 붙여 넣으세요
    return X @ theta

def gradient_descent(X, theta, y, iterations, alpha):
    """다중 선형 회귀 경사 하강법을 구현한 함수"""
    m = len(X)  # 입력 변수 개수 저장

    for _ in range(iterations):
        # 여기에 코드를 작성하세요
        error = prediction(X, theta) - y
        theta = theta - alpha / m * (X.T @ error)
    return theta


# 입력 변수
house_size = np.array([1.0, 1.5, 1.8, 5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 6.0, 7.0, 8.0, 8.5, 9.0, 10.0])  # 집 크기
distance_from_station = np.array([5, 4.6, 4.2, 3.9, 3.9, 3.6, 3.5, 3.4, 2.9, 2.8, 2.7, 2.3, 2.0, 1.8, 1.5, 1.0])  # 지하철역으로부터의 거리 (km)
number_of_rooms = np.array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])  # 방 수

# 목표 변수
house_price = np.array([3, 3.2, 3.6 , 8, 3.4, 4.5, 5, 5.8, 6, 6.5, 9, 9, 10, 12, 13, 15])  # 집 가격

# 설계 행렬 X 정의
X = np.array([
    np.ones(16),
    house_size,
    distance_from_station,
    number_of_rooms
]).T

# 목표 변수 y 정의
y = house_price

# 파라미터 theta 초기화
theta = np.array([0, 0, 0, 0])

# 학습률 0.01로 100번 경사 하강
theta = gradient_descent(X, theta, y, 100, 0.01)

theta

array([0.11484521, 1.21120425, 0.18270523, 0.30060782])

In [3]:
import numpy as np

def normal_equation(X, y):
    """설계 행렬 X와 목표 변수 벡터 y를 받아 정규 방정식으로 최적의 theta를 구하는 함수"""
    # 여기에 코드를 작성하세요
    return np.linalg.pinv(X.T @ X) @ X.T @ y

# 입력 변수
house_size = np.array([1.0, 1.5, 1.8, 5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 6.0, 7.0, 8.0, 8.5, 9.0, 10.0])  # 집 크기
distance_from_station = np.array([5, 4.6, 4.2, 3.9, 3.9, 3.6, 3.5, 3.4, 2.9, 2.8, 2.7, 2.3, 2.0, 1.8, 1.5, 1.0])  # 지하철역으로부터의 거리 (km)
number_of_rooms = np.array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])  # 방 수

# 목표 변수
house_price = np.array([3, 3.2, 3.6 , 8, 3.4, 4.5, 5, 5.8, 6, 6.5, 9, 9, 10, 12, 13, 15])  # 집 가격

# 입력 변수 파라미터 X 정의
X = np.array([
    np.ones(16),
    house_size,
    distance_from_station,
    number_of_rooms
]).T

# 목표 변수 y 정의
y = house_price

# 정규 방정식으로 theta 계산
theta = normal_equation(X, y)
theta

array([ 5.24706322,  1.30727421, -0.68881811, -0.8709494 ])

In [4]:
## 🧮 넘파이: 수학 계산(행렬, 벡터)을 척척 도와줘요!
import numpy as np
## 🧾 판다스: 표(엑셀 같은 것)를 편하게 다루도록 도와줘요!
import pandas as pd
## 🎨 매트플롯립: 그림(그래프)을 그리는 도구예요!
import matplotlib.pyplot as plt
## 🧰 사이킷런: 머신러닝(공부시키기) 도구 상자예요!
from sklearn.model_selection import train_test_split
## 🧰 사이킷런: 머신러닝(공부시키기) 도구 상자예요!
from sklearn.linear_model import LinearRegression
## 🧰 사이킷런: 머신러닝(공부시키기) 도구 상자예요!
from sklearn.metrics import mean_squared_error, r2_score
## 🧰 사이킷런: 머신러닝(공부시키기) 도구 상자예요!
from sklearn.preprocessing import StandardScaler

## 🌬️ (빈 줄) 잠깐 쉬어가요! 코드가 숨을 쉬게 해줘요.

## 📥 데이터 파일(CSV)을 가져와서 표처럼 써요.
df = pd.read_csv('data.csv')
## 👀 데이터의 앞부분만 살짝 보여줘요. 잘 불러왔는지 확인!
df.head()

## 🧱 X: 입력(특징들) 꾸러미를 만들어요. 집의 크기, 방 개수 같은 정보들!
X = df[['feature1', 'feature2', 'feature3']]
## 🎯 y: 정답(목표) 값이에요. 예를 들어 '집값' 같은 거예요!
y = df['target']

## ✂️ 데이터를 공부용(훈련)과 시험용(테스트)으로 나눠요.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## 📏 스케일러: 큰 수, 작은 수의 키를 맞춰서 공부하기 쉽게 만들어요.
scaler = StandardScaler()
## 🧪 스케일러로 '배우고(핏)' 바로 변신(트랜스폼)! 숫자 크기를 고르게 만들어요.
X_train_scaled = scaler.fit_transform(X_train)
## 🔁 이미 배운 스케일 규칙으로 새 데이터도 똑같이 변신시켜요.
X_test_scaled = scaler.transform(X_test)

## 🧠 선형회귀 모델을 만들 준비를 해요. (직선/평면으로 맞춰보기)
model = LinearRegression()
## 📚 모델에게 예시(X, y)를 보여주며 '공부'시키는 단계예요.
model.fit(X_train_scaled, y_train)

## 🔮 공부 끝! 이제 답을 '예측'해봐요.
y_pred = model.predict(X_test_scaled)

## 📏 MSE: 얼마나 틀렸는지(오차)를 숫자로 재봐요. 작을수록 좋아요!
mse = mean_squared_error(y_test, y_pred)
## 🏅 R² 점수: 예측을 얼마나 잘했는지 점수로 보여줘요. 1에 가까울수록 좋아요!
r2 = r2_score(y_test, y_pred)

## 🖨️ 결과를 글자로 보여줘요.
print('MSE:', mse)
## 🖨️ 결과를 글자로 보여줘요.
print('R2:', r2)

## 🌬️ (빈 줄) 잠깐 쉬어가요! 코드가 숨을 쉬게 해줘요.

## 📝 (원래 주석) 아래 줄은 이미 설명이 있어요.
# (선택) 정규방정식으로 직접 해보기 — 아래는 예시 형태예요
## ➕ 1(절편용) 칼럼을 붙여요. y절편이라는 '기본값'을 계산하려고 해요!
X_b = np.c_[np.ones((X_train_scaled.shape[0], 1)), X_train_scaled]
## 📐 정규방정식: 한 번에 딱 맞는 무게추(세타)를 구하는 공식이에요.
theta_best = np.linalg.pinv(X_b.T @ X_b) @ X_b.T @ y_train

## 🔁 이미 배운 스케일 규칙으로 새 데이터도 똑같이 변신시켜요.
X_test_b = np.c_[np.ones((X_test_scaled.shape[0], 1)), X_test_scaled]
## 🤝 행렬곱으로 예측을 만들어요: 입력 X ✖️ 무게추(세타) = 예측값!
y_pred_ne = X_test_b @ theta_best

## 📏 MSE: 얼마나 틀렸는지(오차)를 숫자로 재봐요. 작을수록 좋아요!
mse_ne = mean_squared_error(y_test, y_pred_ne)
## 🏅 R² 점수: 예측을 얼마나 잘했는지 점수로 보여줘요. 1에 가까울수록 좋아요!
r2_ne = r2_score(y_test, y_pred_ne)

## 🖨️ 결과를 글자로 보여줘요.
print('Normal Eq MSE:', mse_ne)
## 🖨️ 결과를 글자로 보여줘요.
print('Normal Eq R2:', r2_ne)

## 🌬️ (빈 줄) 잠깐 쉬어가요! 코드가 숨을 쉬게 해줘요.

## 📝 (원래 주석) 아래 줄은 이미 설명이 있어요.
# (선택) 경사하강법으로 직접 해보기 — 아래는 예시 형태예요
## 🚶 학습률(lr): 한 걸음에 얼마나 움직일지 정해요. 너무 크면 넘어지고, 너무 작으면 느려요.
learning_rate = 0.1
## 🔁 여러 번 반복해서 조금씩 더 똑똑해지게 만들어요(에폭/반복)!
epochs = 2000
## 🤔 이 줄은 프로그램이 잘 돌아가게 도와주는 부분이에요.
m, n = X_train_b.shape
## 🤔 이 줄은 프로그램이 잘 돌아가게 도와주는 부분이에요.
theta = np.zeros(n)

## 🔁 여러 번 반복해서 조금씩 더 똑똑해지게 만들어요(에폭/반복)!
for i in range(epochs):
    ## 🤝 행렬곱으로 예측을 만들어요: 입력 X ✖️ 무게추(세타) = 예측값!
    y_hat = X_train_b @ theta
    ## 🤔 이 줄은 프로그램이 잘 돌아가게 도와주는 부분이에요.
    error = y_hat - y_train.values if hasattr(y_train, 'values') else y_hat - y_train
    ## 🏃 경사하강법: 무게추(세타)를 살짝살짝 고쳐서 더 잘 맞게 해요.
    gradients = (X_train_b.T @ error) / m
    ## 🏃 경사하강법: 무게추(세타)를 살짝살짝 고쳐서 더 잘 맞게 해요.
    theta = theta - learning_rate * gradients
    ## 🖨️ 결과를 글자로 보여줘요.
    if i % 300 == 0:
        ## 📏 MSE: 얼마나 틀렸는지(오차)를 숫자로 재봐요. 작을수록 좋아요!
        mse_gd = (error @ error) / m
        print(f'epoch {i:4d} | MSE ~ {mse_gd:.4f}')

## 🔁 이미 배운 스케일 규칙으로 새 데이터도 똑같이 변신시켜요.
X_test_b = np.c_[np.ones((X_test_scaled.shape[0], 1)), X_test_scaled]
## 🤝 행렬곱으로 예측을 만들어요: 입력 X ✖️ 무게추(세타) = 예측값!
y_pred_gd = X_test_b @ theta

## 📏 MSE: 얼마나 틀렸는지(오차)를 숫자로 재봐요. 작을수록 좋아요!
mse_gd = mean_squared_error(y_test, y_pred_gd)
## 🏅 R² 점수: 예측을 얼마나 잘했는지 점수로 보여줘요. 1에 가까울수록 좋아요!
r2_gd = r2_score(y_test, y_pred_gd)

## 🖨️ 결과를 글자로 보여줘요.
print('GD MSE:', mse_gd)
## 🖨️ 결과를 글자로 보여줘요.
print('GD R2:', r2_gd)

## 🌬️ (빈 줄) 잠깐 쉬어가요! 코드가 숨을 쉬게 해줘요.

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [7]:
import numpy as np

def prediction(X, theta):
    """다중 선형 회귀 가설 함수 😊"""
    return X @ theta  # 행렬곱으로 예측값 계산

def gradient_descent(X, theta, y, iterations, alpha):
    """경사하강법으로 θ 업데이트 🚀"""
    m = len(X)  # 데이터 개수 (집이 몇 채인지)
    for _ in range(iterations):  # 몇 번 반복할까?
        error = prediction(X, theta) - y  # 예측 - 실제 → 오차 계산
        theta = theta - alpha/m * (X.T @ error)  # 오차만큼 θ를 조정
    return theta  # 마지막에 학습된 θ를 돌려줌

def normal_equation(X, y):
    """정규 방정식으로 θ 구하기 📐"""
    return np.linalg.pinv(X.T @ X) @ X.T @ y

# 입력 변수
house_size = np.array([1.0, 1.5, 1.8, 5, 2.0, 2.5, 3.0, 3.5,
                       4.0, 5.0, 6.0, 7.0, 8.0, 8.5, 9.0, 10.0])
distance_from_station = np.array([5, 4.6, 4.2, 3.9, 3.9, 3.6, 3.5, 3.4,
                                  2.9, 2.8, 2.7, 2.3, 2.0, 1.8, 1.5, 1.0])
number_of_rooms = np.array([1, 1, 1, 1, 2, 2, 2, 2,
                            3, 3, 3, 3, 4, 4, 4, 4])
house_price = np.array([3, 3.2, 3.6, 8, 3.4, 4.5, 5, 5.8,
                        6, 6.5, 9, 9, 10, 12, 13, 15])

# 설계 행렬 X (1열은 bias=절편용 1)
X = np.array([
    np.ones(16),          # ① 절편항 → 항상 1 (기본 가격 학습용)
    house_size,           # ② 집 크기 데이터
    distance_from_station,# ③ 지하철 거리 데이터
    number_of_rooms       # ④ 방 개수 데이터
]).T                      # ➡️ 행과 열을 뒤집어서 "집별 데이터"를 행으로 정리

y = house_price

# 초기 θ (0으로 시작)
theta = np.array([0, 0, 0, 0])

# 경사하강법 실행
theta_gd = gradient_descent(X, theta, y, iterations=100, alpha=0.01)
print("경사하강법 결과 θ:", theta_gd)

# 정규 방정식 실행
theta_ne = normal_equation(X, y)
print("정규방정식 결과 θ:", theta_ne)


경사하강법 결과 θ: [0.11484521 1.21120425 0.18270523 0.30060782]
정규방정식 결과 θ: [ 5.24706322  1.30727421 -0.68881811 -0.8709494 ]


In [6]:
print(X)

[[ 1.   1.   5.   1. ]
 [ 1.   1.5  4.6  1. ]
 [ 1.   1.8  4.2  1. ]
 [ 1.   5.   3.9  1. ]
 [ 1.   2.   3.9  2. ]
 [ 1.   2.5  3.6  2. ]
 [ 1.   3.   3.5  2. ]
 [ 1.   3.5  3.4  2. ]
 [ 1.   4.   2.9  3. ]
 [ 1.   5.   2.8  3. ]
 [ 1.   6.   2.7  3. ]
 [ 1.   7.   2.3  3. ]
 [ 1.   8.   2.   4. ]
 [ 1.   8.5  1.8  4. ]
 [ 1.   9.   1.5  4. ]
 [ 1.  10.   1.   4. ]]


In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [14]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [10]:
import pandas as pd

boston_df = pd.read_csv('/content/drive/MyDrive/study/data/boston.csv')
boston_df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [11]:
X = boston_df.drop(columns='MEDV')
X

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [12]:
y = boston_df[['MEDV']]
y

MEDV
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
..    ...
501  22.4
502  20.6
503  23.9
504  22.0
505  11.9

[506 rows x 1 columns]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


(404, 13)
(102, 13)
(404, 1)
(102, 1)


In [17]:
model = LinearRegression()

In [18]:
model.fit(X_train, y_train)

LinearRegression()

In [19]:
model.coef_         # theta1, theta2, theta3

array([[-1.13055924e-01,  3.01104641e-02,  4.03807204e-02,
         2.78443820e+00, -1.72026334e+01,  4.43883520e+00,
        -6.29636221e-03, -1.44786537e+00,  2.62429736e-01,
        -1.06467863e-02, -9.15456240e-01,  1.23513347e-02,
        -5.08571424e-01]])

In [20]:
model.intercept_        # theta0

array([30.24675099])

In [24]:
y_test_prediction = model.predict(X_test)
y_test_prediction

array([[28.99672362],
       [36.02556534],
       [14.81694405],
       [25.03197915],
       [18.76987992],
       [23.25442929],
       [17.66253818],
       [14.34119   ],
       [23.01320703],
       [20.63245597],
       [24.90850512],
       [18.63883645],
       [-6.08842184],
       [21.75834668],
       [19.23922576],
       [26.19319733],
       [20.64773313],
       [ 5.79472718],
       [40.50033966],
       [17.61289074],
       [27.24909479],
       [30.06625441],
       [11.34179277],
       [24.16077616],
       [17.86058499],
       [15.83609765],
       [22.78148106],
       [14.57704449],
       [22.43626052],
       [19.19631835],
       [22.43383455],
       [25.21979081],
       [25.93909562],
       [17.70162434],
       [16.76911711],
       [16.95125411],
       [31.23340153],
       [20.13246729],
       [23.76579011],
       [24.6322925 ],
       [13.94204955],
       [32.25576301],
       [42.67251161],
       [17.32745046],
       [27.27618614],
       [16

In [25]:
mean_squared_error(y_test, y_test_prediction) ** 0.5

4.928602182665332

In [43]:
# 필요한 라이브러리 불러오기 📦
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np

# 1. 당뇨병 데이터 갖고 오기 🍀
diabetes_dataset = datasets.load_diabetes()

# 2. 입력 변수(X) → pandas DataFrame으로 변환
X = pd.DataFrame(diabetes_dataset.data, columns=diabetes_dataset.feature_names)

# 3. 목표 변수(y) → DataFrame으로 변환
y = pd.DataFrame(diabetes_dataset.target, columns=['diabetes'])

# 4. 훈련 데이터와 테스트 데이터 분리 ✂️
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=5
)

# 5. 선형 회귀 모델 불러오기 & 학습시키기 📈
model = LinearRegression()
model.fit(X_train, y_train)

# 6. 테스트 데이터로 예측하기 🔮
y_test_predict = model.predict(X_test)

# 7. RMSE로 성능 평가하기 📊
mse = mean_squared_error(y_test, y_test_predict)
rmse = mse ** 0.5
print("RMSE:", rmse)

RMSE: 54.603912902946895


In [29]:
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [30]:
from sklearn.preprocessing import PolynomialFeatures

In [31]:
ploy_trans = PolynomialFeatures(2)

In [34]:
ploy_data = ploy_trans.fit_transform(boston_df)
ploy_data

array([[1.00000e+00, 6.32000e-03, 1.80000e+01, ..., 2.48004e+01,
        1.19520e+02, 5.76000e+02],
       [1.00000e+00, 2.73100e-02, 0.00000e+00, ..., 8.35396e+01,
        1.97424e+02, 4.66560e+02],
       [1.00000e+00, 2.72900e-02, 0.00000e+00, ..., 1.62409e+01,
        1.39841e+02, 1.20409e+03],
       ...,
       [1.00000e+00, 6.07600e-02, 0.00000e+00, ..., 3.18096e+01,
        1.34796e+02, 5.71210e+02],
       [1.00000e+00, 1.09590e-01, 0.00000e+00, ..., 4.19904e+01,
        1.42560e+02, 4.84000e+02],
       [1.00000e+00, 4.74100e-02, 0.00000e+00, ..., 6.20944e+01,
        9.37720e+01, 1.41610e+02]])

In [35]:
ploy_data.shape

(506, 120)

In [48]:
ploy_feat_names = ploy_trans.get_feature_names_out(boston_df.columns)
ploy_feat_names

array(['1', 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS',
       'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV', 'CRIM^2', 'CRIM ZN',
       'CRIM INDUS', 'CRIM CHAS', 'CRIM NOX', 'CRIM RM', 'CRIM AGE',
       'CRIM DIS', 'CRIM RAD', 'CRIM TAX', 'CRIM PTRATIO', 'CRIM B',
       'CRIM LSTAT', 'CRIM MEDV', 'ZN^2', 'ZN INDUS', 'ZN CHAS', 'ZN NOX',
       'ZN RM', 'ZN AGE', 'ZN DIS', 'ZN RAD', 'ZN TAX', 'ZN PTRATIO',
       'ZN B', 'ZN LSTAT', 'ZN MEDV', 'INDUS^2', 'INDUS CHAS',
       'INDUS NOX', 'INDUS RM', 'INDUS AGE', 'INDUS DIS', 'INDUS RAD',
       'INDUS TAX', 'INDUS PTRATIO', 'INDUS B', 'INDUS LSTAT',
       'INDUS MEDV', 'CHAS^2', 'CHAS NOX', 'CHAS RM', 'CHAS AGE',
       'CHAS DIS', 'CHAS RAD', 'CHAS TAX', 'CHAS PTRATIO', 'CHAS B',
       'CHAS LSTAT', 'CHAS MEDV', 'NOX^2', 'NOX RM', 'NOX AGE', 'NOX DIS',
       'NOX RAD', 'NOX TAX', 'NOX PTRATIO', 'NOX B', 'NOX LSTAT',
       'NOX MEDV', 'RM^2', 'RM AGE', 'RM DIS', 'RM RAD', 'RM TAX',
       'RM PTRATIO', 'RM B', 'RM

In [50]:
X = pd.DataFrame(ploy_data, columns=ploy_feat_names)
X

1     CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  ...  \
0    1.0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  ...   
1    1.0  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  ...   
2    1.0  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  ...   
3    1.0  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  ...   
4    1.0  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  ...   
..   ...      ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  1.0  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  ...   
502  1.0  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  ...   
503  1.0  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  ...   
504  1.0  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  ...   
505  1.0  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  ...   

     PTRATIO^2  PTRATIO B  PTRATIO LSTAT  PTRATIO MEDV          B^2  \
0       234.09   6072.570         76.194        367.20  157529.6100   
1       316.84   7064.820        162.692        384.48  157529.6100   
2       316.84   6992.374         71.734        617.66  154315.4089   
3       349.69   7379.581         54.978        624.58  155732.8369   
4       349.69   7422.030         99.671        676.94  157529.6100   
..         ...        ...            ...           ...          ...   
501     441.00   8231.790        203.070        470.40  153656.1601   
502     441.00   8334.900        190.680        432.60  157529.6100   
503     441.00   8334.900        118.440        501.90  157529.6100   
504     441.00   8262.450        136.080        462.00  154802.9025   
505     441.00   8334.900        165.480        249.90  157529.6100   

       B LSTAT     B MEDV  LSTAT^2  LSTAT MEDV   MEDV^2  
0    1976.5620   9525.600  24.8004     119.520   576.00  
1    3627.6660   8573.040  83.5396     197.424   466.56  
2    1583.1049  13631.201  16.2409     139.841  1204.09  
3    1160.2122  13180.642   8.6436      98.196  1115.56  
4    2115.4770  14367.780  28.4089     192.946  1310.44  
..         ...        ...      ...         ...      ...  
501  3790.5433   8780.576  93.5089     216.608   501.76  
502  3603.8520   8176.140  82.4464     187.048   424.36  
503  2238.5160   9485.910  31.8096     134.796   571.21  
504  2549.5560   8655.900  41.9904     142.560   484.00  
505  3127.5720   4723.110  62.0944      93.772   141.61  

[506 rows x 120 columns]

In [54]:
y = boston_df[['MEDV']]
y

MEDV
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
..    ...
501  22.4
502  20.6
503  23.9
504  22.0
505  11.9

[506 rows x 1 columns]

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

In [56]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [58]:
model.coef_

array([[ 3.35357135e-12,  2.21704332e-12, -3.37719761e-14,
        -1.15682746e-14, -1.87156822e-12,  1.23038452e-11,
        -3.12238130e-13, -3.13136019e-14, -2.72462174e-14,
        -2.36348267e-13,  1.41282385e-15,  3.67330949e-14,
         1.35283494e-14, -8.28464901e-14,  1.00000000e+00,
        -1.77375475e-16, -2.53811729e-15,  1.85047290e-14,
         2.50036537e-14, -3.02994392e-13,  8.68521834e-15,
         1.22558214e-15, -9.78167200e-15,  7.12598383e-14,
        -3.23005511e-15, -9.75200823e-14, -2.60208521e-17,
        -3.86062710e-15, -2.78032805e-15, -5.07406617e-17,
         8.23722601e-16,  1.51463043e-15, -4.41530493e-14,
         2.21610924e-14, -8.32667268e-17, -4.16333634e-16,
         1.51267887e-15, -3.33066907e-16, -3.60822483e-16,
         5.55111512e-17, -1.52655666e-16, -1.08246745e-15,
        -1.07552856e-15, -1.57556260e-15,  2.78809094e-13,
         4.24486835e-15, -8.32667268e-16,  6.63922042e-15,
         4.67074296e-16, -2.22044605e-16,  8.32667268e-1

In [59]:
model.intercept_

array([-3.62021524e-12])

In [60]:
y_test_predict = model.predict(X_test)

In [62]:
mean_squared_error(y_test, y_test_predict) ** 0.5

1.3465428508490357e-12

In [63]:
# 필요한 라이브러리 import
from sklearn import datasets
from sklearn.preprocessing import PolynomialFeatures

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

import pandas as pd

diabetes_dataset = datasets.load_diabetes()  # 데이터 셋 갖고오기

# 여기에 코드를 작성하세요
poly_trans = PolynomialFeatures(2)

# 올바른 데이터 속성(.data)을 사용해서 변환
poly_data = poly_trans.fit_transform(diabetes_dataset.data)

# sklearn 버전에 따라 피처 이름 메서드가 다를 수 있으므로 안전하게 처리
try:
    poly_feat_name = poly_trans.get_feature_names_out(diabetes_dataset.feature_names)
except AttributeError:
    poly_feat_name = poly_trans.get_feature_names(diabetes_dataset.feature_names)

# 데이터프레임으로 저장
X = pd.DataFrame(poly_data, columns=poly_feat_name)

# 확인
# 테스트 코드
X.head()

1       age       sex       bmi        bp        s1        s2        s3  \
0  1.0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1  1.0 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  1.0  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3  1.0 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  1.0  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5  ...      s3^2     s3 s4     s3 s5     s3 s6      s4^2  \
0 -0.002592  0.019907  ...  0.001884  0.000113 -0.000864  0.000766  0.000007   
1 -0.039493 -0.068332  ...  0.005537 -0.002939 -0.005085 -0.006861  0.001560   
2 -0.002592  0.002861  ...  0.001047  0.000084 -0.000093  0.000839  0.000007   
3  0.034309  0.022688  ...  0.001299 -0.001236 -0.000818  0.000337  0.001177   
4 -0.002592 -0.031988  ...  0.000066 -0.000021 -0.000260 -0.000380  0.000007   

      s4 s5     s4 s6      s5^2     s5 s6      s6^2  
0 -0.000052  0.000046  0.000396 -0.000351  0.000311  
1  0.002699  0.003641  0.004669  0.006300  0.008502  
2 -0.000007  0.000067  0.000008 -0.000074  0.000672  
3  0.000778 -0.000321  0.000515 -0.000212  0.000088  
4  0.000083  0.000121  0.001023  0.001492  0.002175  

[5 rows x 66 columns]

In [66]:
# 필요한 라이브러리 import
from sklearn import datasets
from sklearn.preprocessing import PolynomialFeatures

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

import pandas as pd

diabetes_dataset = datasets.load_diabetes()  # 데이터 셋 갖고오기

# 여기에 코드를 작성하세요
polynomial_transformer = PolynomialFeatures(2)  # 2차식 변형기를 정의한다
polynomial_features = polynomial_transformer.fit_transform(diabetes_dataset.data)  # 당뇨 데이터를 2차항 문제로 변환

features = polynomial_transformer.get_feature_names_out(diabetes_dataset.feature_names)  # 입력 변수 이름들도 맞게 바꾼다

X = pd.DataFrame(polynomial_features, columns=features)

# 테스트 코드
X.head()


1       age       sex       bmi        bp        s1        s2        s3  \
0  1.0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1  1.0 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  1.0  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3  1.0 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  1.0  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5  ...      s3^2     s3 s4     s3 s5     s3 s6      s4^2  \
0 -0.002592  0.019907  ...  0.001884  0.000113 -0.000864  0.000766  0.000007   
1 -0.039493 -0.068332  ...  0.005537 -0.002939 -0.005085 -0.006861  0.001560   
2 -0.002592  0.002861  ...  0.001047  0.000084 -0.000093  0.000839  0.000007   
3  0.034309  0.022688  ...  0.001299 -0.001236 -0.000818  0.000337  0.001177   
4 -0.002592 -0.031988  ...  0.000066 -0.000021 -0.000260 -0.000380  0.000007   

      s4 s5     s4 s6      s5^2     s5 s6      s6^2  
0 -0.000052  0.000046  0.000396 -0.000351  0.000311  
1  0.002699  0.003641  0.004669  0.006300  0.008502  
2 -0.000007  0.000067  0.000008 -0.000074  0.000672  
3  0.000778 -0.000321  0.000515 -0.000212  0.000088  
4  0.000083  0.000121  0.001023  0.001492  0.002175  

[5 rows x 66 columns]

In [67]:
# 필요한 라이브러리 import
from sklearn import datasets
from sklearn.preprocessing import PolynomialFeatures

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

import pandas as pd

diabetes_dataset = datasets.load_diabetes()  # 데이터 셋 갖고오기

# 여기에 코드를 작성하세요
polynomial_transformer = PolynomialFeatures(2)  # 2 차식 변형기를 정의한다
polynomial_features = polynomial_transformer.fit_transform(diabetes_dataset.data)  # 당뇨 데이터를 2차항 문제로 변환

features = polynomial_transformer.get_feature_names_out(diabetes_dataset.feature_names)  # 입력 변수 이름들도 맞게 바꾼다

X = pd.DataFrame(polynomial_features, columns=features)

# 목표 변수
y = pd.DataFrame(diabetes_dataset.target, columns=['diabetes'])

# train_test_split를 사용해서 주어진 데이터를 학습, 테스트 데이터로 나눈다
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=5)

# 선형 회귀 모델을 가지고 오고
linear_regression_model = LinearRegression()
linear_regression_model.fit(X_train, y_train)  # 학습 데이터를 이용해서 모델을 학습 시킨다

# 평균 제곱 오차의 루트를 통해서 테스트 데이터에서의 모델 성능 판단
y_test_predict = linear_regression_model.predict(X_test)
mse = mean_squared_error(y_test, y_test_predict)

mse ** 0.5


57.88957704462065